---
- name: Install Postfix
  apt: 
    name: ['postfix', 'postfix-pgsql']
    state: present


- name: Configure Postfix (main.cf)
  template: 
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    mode: 0644
  notify: reload postfix

- name: Configure Postfix (master.cf)
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    mode: 0644
  notify: reload postfix

- name: Configure Postfix (pgsql-boxes.cf)
  template: 
    src: pgsql-boxes.cf.j2
    dest: /etc/postfix/pgsql-boxes.cf
    mode: 0644
  notify: reload postfix

- name: Configure Postfix (pgsql-aliases.cf)
  template: 
    src: pgsql-aliases.cf.j2
    dest: /etc/postfix/pgsql-aliases.cf
    mode: 0644
  notify: reload postfix


    